interactions:
- request:
    body: '{"applicationId": "d89443d2-327c-4a6f-89e5-496bbb0317db", "accountId":
      "99999999-9999-9999-9999-999999999999", "password": "password"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - application/json
      Connection:
      - keep-alive
      Content-Length:
      - '134'
      Content-Type:
      - application/json
      User-Agent:
      - python-requests/2.31.0
    method: POST
    uri: https://share2.dexcom.com/ShareWebServices/Services/General/LoginPublisherAccountById
  response:
    body:
      string: '{"Code":"SSO_InternalError","Message":"Synchronization of SSO account
        during authenticate call failed Time out issue.  AccountId=99999999-9999-9999-9999-999999999999
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountId=''99999999-9999-9999-9999-999999999999''","SubCode":"<OnlineException
        DateThrownLocal=\"2024-07-21T00:59:39.655357323\" DateThrown=\"2024-07-21T00:59:39.655357323Z\"
        ErrorCode=\"SSO_InternalError\" Type=\"15\" Category=\"1\" Severity=\"2\"
        TypeString=\"SingleSignOn\" CategoryString=\"System\" SeverityString=\"Severe\"
        HostName=\"\" HostIP=\"\" Id=\"{55555555-5555-5555-5555-555555555555}\" Message=\"Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountId=99999999-9999-9999-9999-999999999999
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountId=''99999999-9999-9999-9999-999999999999''\"
        FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountId=99999999-9999-9999-9999-999999999999
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountId=''99999999-9999-9999-9999-999999999999''\"
        />","TypeName":"FaultException"}'
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 8a673fe19b964cb1-PHL
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Connection:
      - keep-alive
      Content-Length:
      - '1389'
      Content-Type:
      - application/json
      Date:
      - Sun, 21 Jul 2024 00:59:39 GMT
      Expires:
      - '0'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=0
      Vary:
      - Origin, Accept-Encoding
      pragma:
      - no-cache
      x-content-type-options:
      - nosniff
      x-frame-options:
      - DENY
      x-trace-id:
      - baf88246-faf1-4d3b-8458-9f5d754235e4
      x-xss-protection:
      - '0'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"applicationId": "d89443d2-327c-4a6f-89e5-496bbb0317db", "accountId":
      "99999999-9999-9999-9999-999999999999", "password": "password"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - application/json
      Connection:
      - keep-alive
      Content-Length:
      - '134'
      Content-Type:
      - application/json
      User-Agent:
      - python-requests/2.31.0
    method: POST
    uri: https://share2.dexcom.com/ShareWebServices/Services/General/LoginPublisherAccountById
  response:
    body:
      string: '{"Code":"SSO_InternalError","Message":"Synchronization of SSO account
        during authenticate call failed Time out issue.  AccountId=99999999-9999-9999-9999-999999999999
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountId=''99999999-9999-9999-9999-999999999999''","SubCode":"<OnlineException
        DateThrownLocal=\"2024-07-21T02:23:32.942848154\" DateThrown=\"2024-07-21T02:23:32.942848154Z\"
        ErrorCode=\"SSO_InternalError\" Type=\"15\" Category=\"1\" Severity=\"2\"
        TypeString=\"SingleSignOn\" CategoryString=\"System\" SeverityString=\"Severe\"
        HostName=\"\" HostIP=\"\" Id=\"{55555555-5555-5555-5555-555555555555}\" Message=\"Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountId=99999999-9999-9999-9999-999999999999
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountId=''99999999-9999-9999-9999-999999999999''\"
        FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountId=99999999-9999-9999-9999-999999999999
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountId=''99999999-9999-9999-9999-999999999999''\"
        />","TypeName":"FaultException"}'
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 8a67bac21a7a4cb1-PHL
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Connection:
      - keep-alive
      Content-Length:
      - '1389'
      Content-Type:
      - application/json
      Date:
      - Sun, 21 Jul 2024 02:23:32 GMT
      Expires:
      - '0'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=0
      Vary:
      - Origin, Accept-Encoding
      pragma:
      - no-cache
      x-content-type-options:
      - nosniff
      x-frame-options:
      - DENY
      x-trace-id:
      - a23435b0-45ef-4d4a-b31a-6b8133da58a9
      x-xss-protection:
      - '0'
    status:
      code: 500
      message: Internal Server Error
version: 1
