interactions:
- request:
    body: '{"applicationId": "d89443d2-327c-4a6f-89e5-496bbb0317db", "accountName":
      "u$ern@me", "password": "password"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - application/json
      Connection:
      - keep-alive
      Content-Length:
      - '109'
      Content-Type:
      - application/json
      User-Agent:
      - python-requests/2.31.0
    method: POST
    uri: https://share2.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount
  response:
    body:
      string: '{"Code":"SSO_InternalError","Message":"Synchronization of SSO account
        during authenticate call failed Time out issue.  AccountName=u$ern@me Error
        encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401 UNAUTHORIZED(401)''
        Msg=Cannot Authenticate by AccountName=''u$ern@me''","SubCode":"<OnlineException
        DateThrownLocal=\"2024-07-21T00:59:42.60097406\" DateThrown=\"2024-07-21T00:59:42.60097406Z\"
        ErrorCode=\"SSO_InternalError\" Type=\"15\" Category=\"1\" Severity=\"2\"
        TypeString=\"SingleSignOn\" CategoryString=\"System\" SeverityString=\"Severe\"
        HostName=\"\" HostIP=\"\" Id=\"{55555555-5555-5555-5555-555555555555}\" Message=\"Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=u$ern@me
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''u$ern@me''\"
        FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=u$ern@me
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''u$ern@me''\"
        />","TypeName":"FaultException"}'
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 8a673ff359e14caf-PHL
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Connection:
      - keep-alive
      Content-Length:
      - '1237'
      Content-Type:
      - application/json
      Date:
      - Sun, 21 Jul 2024 00:59:42 GMT
      Expires:
      - '0'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=0
      Vary:
      - Origin, Accept-Encoding
      pragma:
      - no-cache
      x-content-type-options:
      - nosniff
      x-frame-options:
      - DENY
      x-trace-id:
      - 0bcdc445-8f7c-4927-9438-eccd0d2f2890
      x-xss-protection:
      - '0'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"applicationId": "d89443d2-327c-4a6f-89e5-496bbb0317db", "accountName":
      "u$ern@me", "password": "password"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - application/json
      Connection:
      - keep-alive
      Content-Length:
      - '109'
      Content-Type:
      - application/json
      User-Agent:
      - python-requests/2.31.0
    method: POST
    uri: https://share2.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount
  response:
    body:
      string: '{"Code":"SSO_InternalError","Message":"Synchronization of SSO account
        during authenticate call failed Time out issue.  AccountName=u$ern@me Error
        encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401 UNAUTHORIZED(401)''
        Msg=Cannot Authenticate by AccountName=''u$ern@me''","SubCode":"<OnlineException
        DateThrownLocal=\"2024-07-21T02:23:35.58655677\" DateThrown=\"2024-07-21T02:23:35.58655677Z\"
        ErrorCode=\"SSO_InternalError\" Type=\"15\" Category=\"1\" Severity=\"2\"
        TypeString=\"SingleSignOn\" CategoryString=\"System\" SeverityString=\"Severe\"
        HostName=\"\" HostIP=\"\" Id=\"{55555555-5555-5555-5555-555555555555}\" Message=\"Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=u$ern@me
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''u$ern@me''\"
        FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=u$ern@me
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''u$ern@me''\"
        />","TypeName":"FaultException"}'
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 8a67bad4cdb032c6-PHL
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Connection:
      - keep-alive
      Content-Length:
      - '1237'
      Content-Type:
      - application/json
      Date:
      - Sun, 21 Jul 2024 02:23:35 GMT
      Expires:
      - '0'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=0
      Vary:
      - Origin, Accept-Encoding
      pragma:
      - no-cache
      x-content-type-options:
      - nosniff
      x-frame-options:
      - DENY
      x-trace-id:
      - aa1524db-541c-43d0-b71e-bd989c2b3af2
      x-xss-protection:
      - '0'
    status:
      code: 500
      message: Internal Server Error
version: 1
