interactions:
- request:
    body: '{"applicationId": "d89443d2-327c-4a6f-89e5-496bbb0317db", "accountName":
      "username", "password": "password"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - application/json
      Connection:
      - keep-alive
      Content-Length:
      - '108'
      Content-Type:
      - application/json
      User-Agent:
      - python-requests/2.31.0
    method: POST
    uri: https://share2.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount
  response:
    body:
      string: '{"Code":"SSO_InternalError","Message":"Synchronization of SSO account
        during authenticate call failed Time out issue.  AccountName=username Error
        encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401 UNAUTHORIZED(401)''
        Msg=Cannot Authenticate by AccountName=''username''","SubCode":"<OnlineException
        DateThrownLocal=\"2024-07-21T00:59:41.396118418\" DateThrown=\"2024-07-21T00:59:41.396118418Z\"
        ErrorCode=\"SSO_InternalError\" Type=\"15\" Category=\"1\" Severity=\"2\"
        TypeString=\"SingleSignOn\" CategoryString=\"System\" SeverityString=\"Severe\"
        HostName=\"\" HostIP=\"\" Id=\"{55555555-5555-5555-5555-555555555555}\" Message=\"Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=username
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''username''\"
        FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=username
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''username''\"
        />","TypeName":"FaultException"}'
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 8a673fed7bce32cc-PHL
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Connection:
      - keep-alive
      Content-Length:
      - '1233'
      Content-Type:
      - application/json
      Date:
      - Sun, 21 Jul 2024 00:59:41 GMT
      Expires:
      - '0'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=0
      Vary:
      - Origin, Accept-Encoding
      pragma:
      - no-cache
      x-content-type-options:
      - nosniff
      x-frame-options:
      - DENY
      x-trace-id:
      - fd2b0b1e-afd5-4d64-8fe6-e51d04b3c10c
      x-xss-protection:
      - '0'
    status:
      code: 500
      message: Internal Server Error
- request:
    body: '{"applicationId": "d89443d2-327c-4a6f-89e5-496bbb0317db", "accountName":
      "username", "password": "password"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - application/json
      Connection:
      - keep-alive
      Content-Length:
      - '108'
      Content-Type:
      - application/json
      User-Agent:
      - python-requests/2.31.0
    method: POST
    uri: https://share2.dexcom.com/ShareWebServices/Services/General/AuthenticatePublisherAccount
  response:
    body:
      string: '{"Code":"SSO_InternalError","Message":"Synchronization of SSO account
        during authenticate call failed Time out issue.  AccountName=username Error
        encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401 UNAUTHORIZED(401)''
        Msg=Cannot Authenticate by AccountName=''username''","SubCode":"<OnlineException
        DateThrownLocal=\"2024-07-21T02:23:34.376249458\" DateThrown=\"2024-07-21T02:23:34.376249458Z\"
        ErrorCode=\"SSO_InternalError\" Type=\"15\" Category=\"1\" Severity=\"2\"
        TypeString=\"SingleSignOn\" CategoryString=\"System\" SeverityString=\"Severe\"
        HostName=\"\" HostIP=\"\" Id=\"{55555555-5555-5555-5555-555555555555}\" Message=\"Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=username
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''username''\"
        FullText=\"com.dexcom.udp.common.data.exception.OnlineException: Synchronization
        of SSO account during authenticate call failed Time out issue.  AccountName=username
        Error encountered accessing Keycloak endpoint: UAM_ERROR: HttpStatus=''401
        UNAUTHORIZED(401)'' Msg=Cannot Authenticate by AccountName=''username''\"
        />","TypeName":"FaultException"}'
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-Ray:
      - 8a67bace999a4cae-PHL
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Connection:
      - keep-alive
      Content-Length:
      - '1233'
      Content-Type:
      - application/json
      Date:
      - Sun, 21 Jul 2024 02:23:34 GMT
      Expires:
      - '0'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=0
      Vary:
      - Origin, Accept-Encoding
      pragma:
      - no-cache
      x-content-type-options:
      - nosniff
      x-frame-options:
      - DENY
      x-trace-id:
      - e3df828c-70e9-46c6-8984-d5aeca1014f7
      x-xss-protection:
      - '0'
    status:
      code: 500
      message: Internal Server Error
version: 1
