# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* partner_identification_unique_by_category
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 18.0\n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: partner_identification_unique_by_category
#: model:ir.model.fields,field_description:partner_identification_unique_by_category.field_res_partner_id_category__has_unique_numbers
msgid "Enforce unicity"
msgstr ""

#. module: partner_identification_unique_by_category
#: model:ir.model,name:partner_identification_unique_by_category.model_res_partner_id_category
msgid "Partner ID Category"
msgstr ""

#. module: partner_identification_unique_by_category
#: model:ir.model,name:partner_identification_unique_by_category.model_res_partner_id_number
msgid "Partner ID Number"
msgstr ""

#. module: partner_identification_unique_by_category
#. odoo-python
#: code:addons/partner_identification_unique_by_category/models/res_partner_id_number.py:0
msgid ""
"The Id %(name)s in the category %(category_name)s could not be created "
"because it already exists"
msgstr ""

#. module: partner_identification_unique_by_category
#. odoo-python
#: code:addons/partner_identification_unique_by_category/models/res_partner_id_category.py:0
msgid ""
"The category %s can not be set to use unique numbers, because it already "
"contains duplicates."
msgstr ""

#. module: partner_identification_unique_by_category
#: model:ir.model.fields,help:partner_identification_unique_by_category.field_res_partner_id_category__has_unique_numbers
msgid "When set, duplicate numbers will not be allowed for this category."
msgstr ""
